TesteBackendT4W/TesteBackendT4W/Controllers/BookHotelController.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using TesteBackendT4W.Models;
using TesteBackendT4W.Models.api;

namespace TesteBackendT4W.Controllers
{

    /// <summary>
    /// Controller that handles booking requests
    /// </summary>
    public class BookHotelController : Controller{

        private static readonly HttpClient _httpClient = new HttpClient();
        private static readonly string url = "https://pp.cangooroo.net/ws/rest/hotel.svc/Search";


        /// <summary>
        /// Open form to search for rooms
        /// </summary>
        // GET: BookHotel
        [HttpGet]
        public ActionResult Index()
        {
            try
            {
                BookHotelModelView bookHotelModelView = new BookHotelModelView();

                //possible destinations
                ViewBag.Destination = new List<SelectListItem>
                {
                    new SelectListItem() { Text = "MIAMI", Value = "1003944" },
                    new SelectListItem() { Text = "ORLANDO", Value = "1010106" }
                };

                return View(bookHotelModelView);
            }
            catch
            {
                return View("Error");
            }
        }

        /// <summary>
        /// Search for available rooms
        /// </summary>
        /// <param name="bookHotelModelView"></param>
        // POST: BookHotel/Search
        [HttpPost, ActionName("Search")]
        public async Task<ActionResult> SearchAsync(BookHotelModelView bookHotelModelView){
            try
            {

                //fixed value
                bookHotelModelView.MainPaxCountryCodeNationality = "BR";



                //**********************************************************************
                //TEMPORARY FIX
                //CHILD AGES MUST BE PASSED THROUGH A FORM AND SHOULD NOT BE A FIXED VALUE
                //*********************************************************************
                bookHotelModelView.ChildAges = new List<int>();
                for (int i = 0; i <= bookHotelModelView.NumChildren; i++)
                {
                    bookHotelModelView.ChildAges.Add(5);
                }



                //validate the model received by the form 
                if (!ModelState.IsValid){

                    //possible destinations
                    ViewBag.Destination = new List<SelectListItem>{
                        new SelectListItem() { Text = "MIAMI", Value = "1003944" },
                        new SelectListItem() { Text = "ORLANDO", Value = "1010106" }
                    };

                    return View("Index", bookHotelModelView);
                    
                }
                
                //create request
                BookHotelRequest bookHotelRequest = new BookHotelRequest(bookHotelModelView);
                

                //get response
                BookHotelResponse bookHotelResponse =  await SearchHotelRoomAsync(bookHotelRequest);


                //check if the response has any error
                if(bookHotelResponse.Error != null)
                {
                    return View("Index", bookHotelModelView);
                }


                //orders the hotels list by price
                foreach(HotelAvailable hotel in bookHotelResponse.Hotels)
                {
                    hotel.minPrice = int.MaxValue;
                    foreach (Room room in hotel.Rooms)
                    {
                        if (room.TotalSellingPrice.Value < hotel.minPrice) hotel.minPrice = room.TotalSellingPrice.Value; //sets min price for each hotel
                    }
                    
                    hotel.Rooms.Sort((x, y) => x.TotalSellingPrice.Value.CompareTo(y.TotalSellingPrice.Value));
                }
                bookHotelResponse.Hotels.Sort((x, y) => x.minPrice.CompareTo(y.minPrice));



                //returns the hotel list to be viewed
                return View("Search", bookHotelResponse);

                
            }
            catch
            {
                return View("Error");
            }
        }


        /// <summary>
        /// Calls rest API using the request parameter and returns the deserialized response
        /// </summary>
        /// <param name="request"></param>
        [NonAction]
        public async Task<BookHotelResponse> SearchHotelRoomAsync(BookHotelRequest request)
        {

            // Add an Accept header for JSON format
            _httpClient.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
            
            //send POST request
            HttpResponseMessage response = await _httpClient.PostAsJsonAsync(url, request);
                      

            if (response.IsSuccessStatusCode)
            {
                // Parse and returns the response body.
                return response.Content.ReadAsAsync<BookHotelResponse>().Result;  
            }
            
            else
            {
                //request failed
                throw new Exception();
            }
        
        }
        

    }
}

TesteBackendT4W/TesteBackendT4W/Views/BookHotel/Index.cshtml
@model TesteBackendT4W.Models.BookHotelModelView

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reserva de Hotéis</h2>


@using (Html.BeginForm("Search", "BookHotel"))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.DestinationId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.DestinationId,
            ((IEnumerable<SelectListItem>)ViewBag.Destination).Select(option => new SelectListItem {
                Text = option.Text,
                Value = option.Value,
        }), "Escolha uma opção...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DestinationId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.NumNights, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumNights, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumNights, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CheckinDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CheckinDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CheckinDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumAdults, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumAdults, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumAdults, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.NumChildren, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumChildren, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumChildren, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Buscar" class="btn btn-default" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TesteBackendT4W/TesteBackendT4W/Views/BookHotel/Search.cshtml
@model TesteBackendT4W.Models.api.BookHotelResponse

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Resultados</h2>

<div>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.TotalHotelResults)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalHotelResults)
        </dd>

    </dl>


    <p>
        @if (Request.UrlReferrer != null)
        {
            <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Realizar Nova Busca</a><br />
        }
    </p>


    @foreach (var hotel in Model.Hotels)
    {
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(modelItem => hotel.HotelId)
                </th>
                @*<th>
                        @Html.DisplayNameFor(modelItem => hotel.IsRecommended)
                    </th>*@
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => hotel.HotelId)
                    @Html.ActionLink("Detalhes", "Details", new { controller = "Hotel", id = hotel.HotelId })
                </td>

                @*<td>
                        @Html.DisplayFor(modelItem => hotel.IsRecommended)
                    </td>*@



                @foreach (var room in hotel.Rooms)
                {
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => room.BoardDescription)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.IsAvailable)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.IsPrePayment)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.MoreInformation)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.NumAdults)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.PayDirectToHotel)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.Quantity)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => room.RoomDescription)
                            </th>
                            <th></th>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => room.BoardDescription)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.IsAvailable)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.IsPrePayment)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.MoreInformation)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.NumAdults)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.PayDirectToHotel)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.Quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => room.RoomDescription)
                            </td>



                        </tr>
                    </table>


                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => room.TotalSellingPrice.Currency)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => room.TotalSellingPrice.Currency)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => room.TotalSellingPrice.Value)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => room.TotalSellingPrice.Value)
                        </dd>

                    </dl>

                }



            </tr>
        </table>
    }




</div>